CREATE TABLE LOT(
    ID INTEGER PRIMARY KEY AUTOINCREMENT  NOT NULL,
    NAME VARCHAR(20),
    PRODUCT_ID        INTEGER,
    QTY                 FLOAT,
    STOCK_LOCATION_ID INTEGER,


    FOREIGN KEY(STOCK_LOCATION_ID) REFERENCES STOCK_LOCATION(ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
);
