'id', 'activity_ids', 'activity_state', 'activity_user_id', 'activity_type_id', 'activity_type_icon',
'activity_date_deadline', 'my_activity_date_deadline', 'activity_summary', 'activity_exception_decoration', 
'activity_exception_icon', 'activity_calendar_event_id', 'message_is_follower', 'message_follower_ids', 
'message_partner_ids', 'message_ids', 'has_message', 'message_unread', 'message_unread_counter', 'message_needaction',
'message_needaction_counter', 'message_has_error', 'message_has_error_counter', 'message_attachment_count', 
'message_main_attachment_id', 'website_message_ids', 'message_has_sms_error', 'price', 'price_extra', 'lst_price',
'default_code', 'code', 'partner_ref', 'active', 'product_tmpl_id', 'barcode', 'product_template_attribute_value_ids'
, 'product_template_variant_value_ids', 'combination_indices', 'is_product_variant', 'standard_price', 'volume', 'weight'
, 'pricelist_item_count', 'packaging_ids', 'image_variant_1920', 'image_variant_1024', 'image_variant_512', 
'image_variant_256', 'image_variant_128', 'can_image_variant_1024_be_zoomed', 'image_1920', 'image_1024', 'image_512',
'image_256', 'image_128', 'can_image_1024_be_zoomed', '__last_update', 'display_name', 'create_uid',
'create_date', 'write_uid', 'write_date', 'tax_string', 'stock_quant_ids', 'stock_move_ids', 
'nbr_moves_in', 'nbr_moves_out', 'nbr_reordering_rules', 'reordering_min_qty', 'reordering_max_qty'
, 'putaway_rule_ids', 'storage_category_capacity_ids', 'show_on_hand_qty_status_button', 
'show_forecasted_qty_status_button', 'purchased_product_qty', 'value_svl', 'quantity_svl',
'stock_valuation_layer_ids', 'valuation', 'cost_method', 'purchase_order_line_ids', 'sales_count',
'family_id', 'sub_family_id', 'simulation_applied', 'enable_virtual_stock', 'enable_virtual_stock_location', 'virtual_stock_date',
'virtual_stock_qty_init', 'virtual_stock_qty_now', 'virtual_stock_line_ids', 'name', 'sequence', 'description'
'description_purchase', 'description_sale', 'detailed_type', 'type', 'categ_id', 'currency_id', 'cost_currency_id',
'list_price', 'volume_uom_name', 'weight_uom_name', 'sale_ok', 'purchase_ok', 'pricelist_id', 'uom_id', 'uom_name',
'uom_po_id', 'company_id', 'seller_ids', 'variant_seller_ids', 'color', 'attribute_line_ids',
'valid_product_template_attribute_line_ids', 'product_variant_ids', 'product_variant_id', 'product_variant_count', 
'has_configurable_attributes', 'product_tooltip', 'priority', 'taxes_id', 'supplier_taxes_id', 'property_account_income_id', 
'property_account_expense_id', 'account_tag_ids', 'responsible_id', 'property_stock_production', 'property_stock_inventory',
'sale_delay', 'tracking', 'description_picking', 'description_pickingout', 'description_pickingin', 'location_id', 'warehouse_id',
'has_available_route_ids', 'route_ids', 'route_from_categ_ids', 'asset_category_id', 'deferred_revenue_category_id', 
'property_account_creditor_price_difference', 'purchase_method', 'purchase_line_warn', 'purchase_line_warn_msg', 'allow_negative_stock',
'motif_ids', 'service_type', 'sale_line_warn', 'sale_line_warn_msg', 'expense_policy', 'visible_expense_policy', 'visible_qty_configurator', 
'invoice_policy', 'type_tap_product', 'type_tax_product', 'ignore_g50_tap', 'product_tag_ids', 'service_to_purchase', 'uom_cat_id',
'has_uom2', 'has_uom3', 'uom2_main', 'uom2_qty_available', 'uom2_id', 'uos2_conv', 'uom2_is_sale_default', 'uom3_main',
'uom3_qty_available', 'uom3_id', 'uos3_conv', 'is_import', 'is_import_landed', 'importation_hist_count', 'hs_code', 
'process_import_cats', 'landed_price_type', 'is_consumable_stockable', 'stock_niveau_min', 'stock_niveau_critique',
'validator', 'is_expense', 'expenses_count'])